name: React with Jest CI

on:
  pull_request:
    branches:
      - stable

jobs:
  test-coverage:
    name: React with Test and Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: yarn install --frozen-lockfile
      - run: yarn test:ci